config/routes.rb
Rails.application.routes.draw do
  resources :diaries do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
    validates:title,:body,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @text = 'indexアクションが実行されました'
    end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[ show edit update destroy ]
  before_action :set_q, only: [:index, :search]
  
  
  # GET /diaries or /diaries.json
  def index
    @diaries = @q.result
  end
  # GET /diaries/1 or /diaries/1.json
  def show
    #@diary = Diary.find(params[:id])
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries or /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to diary_url(@diary), notice: "日記の作成が完了しました。" }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1 or /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to diary_url(@diary), notice: "日記が更新されました。" }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1 or /diaries/1.json
  def destroy
    @diary.destroy

    respond_to do |format|
      format.html { redirect_to diaries_url, notice: "日記を削除しました。" }
      format.json { head :no_content }
    end
  end
  
  def search
    @results = @q.result
  end
  
  private
  
    def set_q
    @q = Diary.ransack(params[:q])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
      
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.require(:diary).permit(:title, :body, :kept_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/books/index.html.erb
<h1>書籍一覧</h1>
<p><%= @text %></p>

app/views/diaries/_form.html.erb
<%= form_with(model: diary) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :day %>
    <%= form.datetime_field :kept_at %>
  </div>
  
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>編集画面</h1>

<%= render 'form', diary: @diary %>

<%= link_to '確認', @diary %> |
<%= link_to '戻る', diaries_path %>

app/views/diaries/index.html.erb
<h1>タイトル検索</h1>
<%= search_form_for @q, url: search_diaries_path do |f| %>
  <%= f.label :title_cont, 'タイトル名' %>
  <%= f.search_field :title_cont %>
  <br>
  <%= f.submit '検索' %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>日記一覧</h1>

<table>
    <thead>
    <tr>
      <th><%= sort_link(@q, :id, "ID") %></th>
      <th><%= sort_link(@q, :tittle, "タイトル") %></th>
      <th><%= sort_link(@q, :kept_at, "日にち") %></th>
      <th><%= sort_link(@q, :created_at, "作成日時") %></th>
      <th><%= sort_link(@q, :updated_at, "更新日時") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%=diary.id %></td>
        <td><%= link_to diary.title, diary %></td>
        <td><%= diary.kept_at.strftime("%Y/%m/%d") if diary.kept_at.present? %></td>
        
        <td><%= l diary.created_at %></td>
        <td><%= l diary.updated_at %></td>
        <td><%= link_to ' 編集 ', edit_diary_path(diary) %></td>
        <td><%= link_to ' 削除 ', diary, method: :delete, data: { confirm: '本当に消してもいいですか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日記を新規作成', new_diary_path %>

app/views/diaries/new.html.erb
<h1>New Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to '戻る', diaries_path %>

app/views/diaries/search.html.erb
<h1>検索結果</h1>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>本文</th>
      <th>日にち</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |diary| %>
      <tr>
        <td><%= diary.id %></td>
        <td><%= diary.title %></td>
        <td><%= diary.body %></td>
        <td><%= diary.kept_at.strftime("%Y/%m/%d") if diary.kept_at.present? %></td>
        <td><%= l diary.created_at %></td>
        <td><%= l diary. updated_at%></td>
        <td><%= link_to '確認', diary %></td>
        <td><%= link_to '編集', edit_diary_path(diary) %></td>
        <td><%= link_to '削除', diary, method: :delete, data: { confirm: '本当に消してもいいですか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '一覧画面に戻る', diaries_path %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>ID:</strong>
  <%= @diary.id %>
</p>

<p>
  <strong>タイトル:</strong>
  <%= @diary.title %>
</p>

<p>
  <strong>本文:</strong>
  <%= @diary.body %>
</p>

<p>
  <strong>日にち:</strong>
  <%= @diary.kept_at.strftime("%Y/%m/%d") if @diary.kept_at.present? %>
</p>

<p>
  <strong>登録日時:</strong>
  <%= l @diary.created_at %>
</p>

<p>
  <strong>更新日時:</strong>
  <%= l @diary. updated_at%>
</p>

<%= link_to '編集', edit_diary_path(@diary) %> |
<%= link_to '戻る', diaries_path %> |
<%= link_to ' 削除 ', @diary, method: :delete, data: { confirm: '本当に消してもいいですか?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>